import { TDisplaySettings } from 'src/types/global';

export const MINI_MAP_TERRAIN_DISPLAY: TDisplaySettings = {
  landform: true,
  biome: false,
  nationFill: false,
  nationBorders: false,
  ethnicFill: false,
  ethnicBorders: false,
  provinceBorders: false,
  population: false,
  temperature: false,
  precipitation: false,
  rainShadow: false,
  economy: false,
  rivers: false,
  labels: false,
  ethnicLabels: false,
  cellData: false,
  landformRelief: false,
  biomeRelief: false,
  isometric: false,
  threeDim: false,
};

export const MINI_MAP_BIOME_DISPLAY: TDisplaySettings = {
  landform: false,
  biome: true,
  nationFill: false,
  nationBorders: false,
  ethnicFill: false,
  ethnicBorders: false,
  provinceBorders: false,
  population: false,
  temperature: false,
  precipitation: false,
  rainShadow: false,
  economy: false,
  rivers: false,
  labels: false,
  ethnicLabels: false,
  cellData: false,
  landformRelief: false,
  biomeRelief: false,
  isometric: false,
  threeDim: false,
};
